CREATE TABLE [Census].[Finance] (
    [ID_Code]                             VARCHAR (50)   NOT NULL,
    [Item_Code]                           VARCHAR (50)   NOT NULL,
    [Year_of_Data]                        VARCHAR (50)   NOT NULL,
    [ID_Name]                             NVARCHAR (255) NULL,
    [County_Name]                         NVARCHAR (255) NULL,
    [FIPS_State]                          NVARCHAR (255) NULL,
    [FIPS_County]                         NVARCHAR (255) NULL,
    [FIPS_Place]                          BIGINT         NULL,
    [Population]                          INT            NULL,
    [Population_Year]                     BIGINT         NULL,
    [Enrollment]                          NVARCHAR (255) NULL,
    [Enrollment_Year]                     NVARCHAR (255) NULL,
    [Function_Code_For_Special_Districts] NVARCHAR (255) NULL,
    [School_Level_Code]                   NVARCHAR (255) NULL,
    [Fiscal_Year_Ending]                  BIGINT         NULL,
    [Survey_Year]                         BIGINT         NULL,
    [Joined_ID_Code]                      NVARCHAR (255) NULL,
    [Amount_Thousands_Dollars]            INT            NULL,
    [Imputation_Type_Item_Data_Flag]      NVARCHAR (255) NULL,
    [ID_Code_State]                       NVARCHAR (255) NULL,
    [State]                               NVARCHAR (255) NULL,
    [Government_Type]                     NVARCHAR (255) NULL,
    [County_Type]                         NVARCHAR (255) NULL,
    [Unit_Identifier]                     NVARCHAR (255) NULL,
    [Government_Flag]                     NVARCHAR (255) NULL,
    CONSTRAINT [PK_Finance2] PRIMARY KEY CLUSTERED ([ID_Code] ASC, [Item_Code] ASC, [Year_of_Data] ASC)
);

