CREATE TABLE [Staging].[MasterPnL] (
    [Type]               NVARCHAR (255) NULL,
    [Mission]            NVARCHAR (255) NULL,
    [Excel_Segment 1]    NVARCHAR (255) NULL,
    [Excel_Segment 2]    NVARCHAR (255) NULL,
    [Excel_Segment 3]    NVARCHAR (255) NULL,
    [Memo 1]             NVARCHAR (255) NULL,
    [Memo 2]             NVARCHAR (255) NULL,
    [Memo 3]             NVARCHAR (255) NULL,
    [Year]               FLOAT (53)     NULL,
    [Aggregated value]   FLOAT (53)     NULL,
    [Gov Type]           NVARCHAR (255) NULL,
    [State]              FLOAT (53)     NULL,
    [Source]             NVARCHAR (255) NULL,
    [Grant]              NVARCHAR (255) NULL,
    [Year-StateID]       NVARCHAR (255) NULL,
    [MissionID]          FLOAT (53)     NULL,
    [SegmentID]          FLOAT (53)     NULL,
    [Code]               NVARCHAR (255) NULL,
    [Census description] NVARCHAR (255) NULL,
    [Agency Name]        NVARCHAR (255) NULL,
    [Account Name]       NVARCHAR (255) NULL,
    [Segment 1]          NVARCHAR (255) NULL,
    [Mission New]        NVARCHAR (255) NULL,
    [Segment 2]          NVARCHAR (255) NULL,
    [Segment 3]          NVARCHAR (255) NULL,
    [PBI_Segment 1]      NVARCHAR (255) NULL,
    [PBI_Segment 2]      NVARCHAR (255) NULL,
    [PBI_Segment 3]      NVARCHAR (255) NULL, 
    [FileVersionId] INT NULL
);

